package com.jagex.network;/* Class202 - Decompiled by JODE
 * Visit http://jode.sourceforge.net/
 */

public class IncommingPacket {
    public static IncommingPacket SET_CAMERA_LOOK_PACKET;
    public static IncommingPacket aClass202_2151;
    public static IncommingPacket FRIENDS_PACKET;
    public static IncommingPacket RECIEVE_CLAN_CHAT_MESSAGE;
    public static IncommingPacket aClass202_2154;
    public static IncommingPacket CLOSE_INTERFACE_PACKET;
    public static IncommingPacket PLAYER_UNDER_NPC_PRIORITY_PACKET;
    public static IncommingPacket aClass202_2157;
    public static IncommingPacket aClass202_2158;
    public static IncommingPacket MUSIC_EFFECT_PACKET;
    public static IncommingPacket aClass202_2160;
    public static IncommingPacket WORLD_LIST_PACKET;
    public static IncommingPacket aClass202_2162;
    public static IncommingPacket aClass202_2163;
    public static IncommingPacket INTERFACE_PACKET;
    public static IncommingPacket aClass202_2166;
    public static IncommingPacket OPEN_URL_PACKET;
    public static IncommingPacket aClass202_2168;
    public static IncommingPacket ICOMPONENT_TEXT_PACKET;
    public static IncommingPacket PROJECTILE_PACKET;
    public static IncommingPacket SHAKE_CAMERA_PACKET;
    public static IncommingPacket ICOMPONENT_ITEM_MODEL_ROTATION_PACKET;
    public static IncommingPacket PLAYER_ON_ICOMPONENT_PACKET;
    public static IncommingPacket aClass202_2174;
    public static IncommingPacket RUN_ENERGY_PACKET;
    public static IncommingPacket aClass202_2176;
    public static IncommingPacket aClass202_2177;
    public static IncommingPacket aClass202_2178;
    public static IncommingPacket aClass202_2179;
    public static IncommingPacket SEND_FRIEND_QUICK_CHAT_MESSAGE_PACKET;
    public static IncommingPacket NPC_ICOMPONENT_PACKET;
    public static IncommingPacket aClass202_2182;
    public static IncommingPacket RECEIVE_PERSONAL_MESSAGE_PACKET;
    public static IncommingPacket aClass202_2184;
    public static IncommingPacket aClass202_2185;
    public static IncommingPacket aClass202_2186;
    public static IncommingPacket aClass202_2188;
    public static IncommingPacket GAME_PANE_PACKET;
    public static IncommingPacket ICOMPONENT_SETTINGS_PACKET;
    public static IncommingPacket ICOMPONENT_SCROLL_PACKET;
    public static IncommingPacket LOAD_MAP_SCENE_PACKET;
    public static IncommingPacket aClass202_2193;
    public static IncommingPacket aClass202_2194;
    public static IncommingPacket aClass202_2195;
    public static IncommingPacket RESET_CAMERA_PACKET;
    public static IncommingPacket WORLD_TILE_PACKET;
    public static IncommingPacket SWITCH_ITEMS_LOOK_PACKET;
    public static IncommingPacket aClass202_2198;
    public static IncommingPacket aClass202_2199;
    public static IncommingPacket NPC_UPDATE_PACKET;
    public static IncommingPacket aClass202_2201;
    public static IncommingPacket SPAWN_OBJECT_PACKET;
    public static IncommingPacket aClass202_2203;
    public static IncommingPacket aClass202_2204;
    public static IncommingPacket SET_MOUSE_PACKET;
    public static IncommingPacket CONFIG2_PACKET;
    public static IncommingPacket OPEN_INTERFACE_NPC;
    public static IncommingPacket aClass202_2208;
    public static IncommingPacket aClass202_2209;
    public static IncommingPacket GLOBAL_STRING_LONG_PACKET;
    public static IncommingPacket IGNORES_PACKET;
    public static IncommingPacket ICOMPONENT_CLICKABLE_PACKET;
    public static IncommingPacket GLOBAL_CONFIG_INTVAL_PACKET;
    public static IncommingPacket LARGE_NPC_UPDATE_PACKET;
    public static IncommingPacket aClass202_2215;
    public static IncommingPacket ITEMS_PACKET;
    public static IncommingPacket aClass202_2217;
    public static IncommingPacket SET_ICOMPONENT_POSITION;
    public static IncommingPacket RECEIVE_FRIEND_CHAT_QUICK_MESSAGE_PACKET;
    public static IncommingPacket aClass202_2220;
    public static IncommingPacket aClass202_2221;
    public static IncommingPacket GLOBAL_STRING_SHORT_PACKET;
    public static IncommingPacket aClass202_2223;
    public static IncommingPacket SET_CAMERA_POS_PACKET;
    public static IncommingPacket PRIVATE_GAME_BAR_STAGE_PACKET;
    public static IncommingPacket OBJECT_ANIMATION_PACKET;
    public static IncommingPacket aClass202_2227 = new IncommingPacket(0, -1);
    public static IncommingPacket aClass202_2228;
    public static IncommingPacket SOUND_INDEX15;
    public static IncommingPacket ICOMPONENT_COLOR_PACKET;
    public static IncommingPacket aClass202_2231;
    public static IncommingPacket aClass202_2232;
    public static IncommingPacket CUTSCENE_PACKET;
    public static IncommingPacket aClass202_2234;
    public static IncommingPacket CONFIG_BY_FILE2_PACKET;
    public static IncommingPacket aClass202_2236;
    public static IncommingPacket aClass202_2237;
    public static IncommingPacket aClass202_2238;
    public static IncommingPacket aClass202_2239;
    public static IncommingPacket GRAPHICS_PACKET;
    public static IncommingPacket CAMERA_ROTATION_PACKET;
    public static IncommingPacket aClass202_2242;
    public static IncommingPacket LOBBY_LOGOUT_PACKET;
    public static IncommingPacket FRIENDS_CHAT_CHANNEL_PACKET;
    public static IncommingPacket CLANCHAT_MANAGER;
    public static IncommingPacket PLAYER_UPDATE_PACKET;
    public static IncommingPacket aClass202_2247;
    public static IncommingPacket aClass202_2248;
    public static IncommingPacket aClass202_2249;
    public static IncommingPacket aClass202_2250;
    public static IncommingPacket aClass202_2251;
    public static IncommingPacket SEND_PRIVATE_MESSAGE_PACKET;
    public static IncommingPacket ICOMPONENT_ANIMATION_PACKET;
    public static IncommingPacket RECEIVE_PRIVATE_QUICK_CHAT_MESSAGE_PACKET;
    public static IncommingPacket MEMORY_MANAGEMENT;
    public static IncommingPacket PUBLIC_MESSAGE_PACKET;
    public static IncommingPacket TILE_MESSAGE_PACKET;
    public static IncommingPacket REMOVE_GROUND_ITEM_PACKET;
    public static IncommingPacket aClass202_2259;
    public static IncommingPacket CONFIG1_PACKET;
    public static IncommingPacket aClass202_2261;
    public static IncommingPacket ICOMPONENT_HIDE_PACKET;
    public static IncommingPacket OPEN_INTERFACE_PLAYER;
    public static IncommingPacket ICOMPONENT_MODEL_PACKET;
    public static IncommingPacket aClass202_2265;
    public static IncommingPacket RECEIVE_QUICK_PRIVATE_MESSAGE;
    public static IncommingPacket aClass202_2267;
    public static IncommingPacket PLAYER_OPTION_PACKET;
    public static IncommingPacket RUN_SCRIPT_PACKET;
    public static IncommingPacket aClass202_2270;
    public static IncommingPacket ICOMPONENT_SPRITE_PAKCET;
    public static IncommingPacket ICOMPONENT_FONTID_PACKET;
    public static IncommingPacket OPEN_INTERFACE_OBJECT;
    public static IncommingPacket aClass202_2274;
    public static IncommingPacket SEND_GROUND_ITEM_PACKET;
    public static IncommingPacket aClass202_2276;
    public static IncommingPacket FULL_PLAYER_ON_ICOMPONENT_PACKET;
    public static IncommingPacket IGNORE_PACKET;
    public static IncommingPacket MUSIC_PACKET;
    public static IncommingPacket DESTROY_OBJECT_PACKET;
    public static IncommingPacket STOP_CAMERA_SHAKE_PACKET;
    public static IncommingPacket SECURITY_PACKET;
    public static IncommingPacket aClass202_2283;
    public static IncommingPacket aClass202_2284;
    public static IncommingPacket BLACK_OUT_PACKET;
    public static IncommingPacket MESSAGE_PACKET;
    public static IncommingPacket aClass202_2287;
    public static IncommingPacket ITEMS_UPDATE_PACKET;
    public static IncommingPacket RECEIVE_FRIEND_CHAT_MESSAGE_PACKET;
    public static IncommingPacket aClass202_2290;
    public static IncommingPacket SYSTEM_UPDATE_PACKET;
    public static IncommingPacket RECEIVE_PRIVATE_MESSAGE_PACKET;
    public static IncommingPacket aClass202_2293;
    public static IncommingPacket LOAD_MAP_SCENE_DYNAMIC_PACKET;
    public static IncommingPacket RESET_SOUNDS_PACKET;
    public static IncommingPacket SKILL_LEVEL_PACKET;
    public static IncommingPacket aClass202_2297;
    public static IncommingPacket aClass202_2298;
    public static IncommingPacket aClass202_2299;
    public static IncommingPacket HINT_ICON_PACKET;
    public static IncommingPacket CLIENT_CONSOLE_COMMAND_PACKET;
    public static IncommingPacket ITEM_ON_ICOMPONENT_PACKET;
    public static IncommingPacket SYNCBOT_PANEL_INITIALIZER;
    public static IncommingPacket KEEP_ALIVE_PACKET;
    public static IncommingPacket GLOBAL_CONFIG_BYTEVAL_PACKET;
    public static IncommingPacket aClass202_2305;
    public static IncommingPacket aClass202_2306;
    public static IncommingPacket aClass202_2307;
    public static IncommingPacket LOGOUT_PACKET;
    public static IncommingPacket aClass202_2309;
    public static IncommingPacket CONFIG_BY_FILE1_PACKET;
    public static IncommingPacket SYNCBOT_INFORMATON;

    static {
        RECEIVE_QUICK_PRIVATE_MESSAGE = new IncommingPacket(1, -1);
        FRIENDS_PACKET = new IncommingPacket(2, -2);
        RECIEVE_CLAN_CHAT_MESSAGE = new IncommingPacket(3, -1);
        aClass202_2154 = new IncommingPacket(4, 19);
        CLOSE_INTERFACE_PACKET = new IncommingPacket(5, 4);
        PLAYER_UNDER_NPC_PRIORITY_PACKET = new IncommingPacket(6, 1);
        aClass202_2157 = new IncommingPacket(7, 4);
        aClass202_2158 = new IncommingPacket(8, -1);
        MUSIC_EFFECT_PACKET = new IncommingPacket(9, 6);
        SET_MOUSE_PACKET = new IncommingPacket(10, -1);
        WORLD_LIST_PACKET = new IncommingPacket(11, -2);
        aClass202_2162 = new IncommingPacket(12, 1);
        aClass202_2163 = new IncommingPacket(13, 2);
        INTERFACE_PACKET = new IncommingPacket(14, 23);
        aClass202_2195 = new IncommingPacket(15, 1);
        aClass202_2166 = new IncommingPacket(16, 0);
        OPEN_URL_PACKET = new IncommingPacket(17, -2);
        aClass202_2168 = new IncommingPacket(18, 0);
        aClass202_2186 = new IncommingPacket(19, 2);
        PROJECTILE_PACKET = new IncommingPacket(20, 16);
        aClass202_2151 = new IncommingPacket(21, 6);
        ICOMPONENT_ITEM_MODEL_ROTATION_PACKET = new IncommingPacket(22, 10);
        PLAYER_ON_ICOMPONENT_PACKET = new IncommingPacket(23, 4);
        aClass202_2174 = new IncommingPacket(24, -1);
        RUN_ENERGY_PACKET = new IncommingPacket(25, 1);
        aClass202_2176 = new IncommingPacket(26, 8);
        aClass202_2177 = new IncommingPacket(27, 28);
        aClass202_2284 = new IncommingPacket(28, 7);
        aClass202_2179 = new IncommingPacket(29, 9);
        SEND_FRIEND_QUICK_CHAT_MESSAGE_PACKET = new IncommingPacket(30, -1);
        NPC_ICOMPONENT_PACKET = new IncommingPacket(31, 8);
        RECEIVE_FRIEND_CHAT_QUICK_MESSAGE_PACKET = new IncommingPacket(32, -1);
        RECEIVE_PERSONAL_MESSAGE_PACKET = new IncommingPacket(33, -1);
        GLOBAL_STRING_LONG_PACKET = new IncommingPacket(34, -2);
        aClass202_2185 = new IncommingPacket(35, 0);
        aClass202_2160 = new IncommingPacket(36, 29);
        aClass202_2259 = new IncommingPacket(37, 4);
        aClass202_2188 = new IncommingPacket(38, 6);
        GAME_PANE_PACKET = new IncommingPacket(39, 19);
        ICOMPONENT_SETTINGS_PACKET = new IncommingPacket(40, 12);
        ICOMPONENT_SCROLL_PACKET = new IncommingPacket(41, 6);
        LOAD_MAP_SCENE_PACKET = new IncommingPacket(42, -2);
        aClass202_2193 = new IncommingPacket(43, -1);
        SHAKE_CAMERA_PACKET = new IncommingPacket(44, 6);
        DESTROY_OBJECT_PACKET = new IncommingPacket(45, 2);
        aClass202_2209 = new IncommingPacket(46, 4);
        aClass202_2184 = new IncommingPacket(47, 8);
        aClass202_2198 = new IncommingPacket(48, 10);
        aClass202_2199 = new IncommingPacket(49, -1);
        ICOMPONENT_CLICKABLE_PACKET = new IncommingPacket(50, 5);
        aClass202_2201 = new IncommingPacket(51, 2);
        aClass202_2194 = new IncommingPacket(52, 11);
        aClass202_2203 = new IncommingPacket(53, 20);
        aClass202_2238 = new IncommingPacket(54, 10);
        IGNORES_PACKET = new IncommingPacket(55, -2);
        CONFIG2_PACKET = new IncommingPacket(56, 6);
        OPEN_INTERFACE_NPC = new IncommingPacket(57, 25);
        aClass202_2208 = new IncommingPacket(58, 2);
        LOBBY_LOGOUT_PACKET = new IncommingPacket(59, 0);
        LOGOUT_PACKET = new IncommingPacket(60, 0);
        CLIENT_CONSOLE_COMMAND_PACKET = new IncommingPacket(61, -1);
        aClass202_2261 = new IncommingPacket(62, -2);
        GLOBAL_CONFIG_INTVAL_PACKET = new IncommingPacket(63, 6);
        LARGE_NPC_UPDATE_PACKET = new IncommingPacket(64, -2);
        aClass202_2215 = new IncommingPacket(65, 7);
        aClass202_2204 = new IncommingPacket(66, 0);
        aClass202_2217 = new IncommingPacket(67, 0);
        SET_ICOMPONENT_POSITION = new IncommingPacket(68, 8);
        BLACK_OUT_PACKET = new IncommingPacket(69, 1);
        SOUND_INDEX15 = new IncommingPacket(70, 6);
        aClass202_2221 = new IncommingPacket(71, 9);
        NPC_UPDATE_PACKET = new IncommingPacket(72, -2);
        aClass202_2223 = new IncommingPacket(73, 4);
        SET_CAMERA_POS_PACKET = new IncommingPacket(74, 6);
        PRIVATE_GAME_BAR_STAGE_PACKET = new IncommingPacket(75, 1);
        OBJECT_ANIMATION_PACKET = new IncommingPacket(76, 9);
        ITEMS_PACKET = new IncommingPacket(77, -2);
        aClass202_2228 = new IncommingPacket(78, 0);
        HINT_ICON_PACKET = new IncommingPacket(79, 14);
        ICOMPONENT_COLOR_PACKET = new IncommingPacket(80, 6);
        CONFIG_BY_FILE2_PACKET = new IncommingPacket(81, 6);
        aClass202_2248 = new IncommingPacket(82, 1);
        aClass202_2247 = new IncommingPacket(83, -1);
        aClass202_2270 = new IncommingPacket(84, 6);
        CLANCHAT_MANAGER = new IncommingPacket(85, -2);
        aClass202_2290 = new IncommingPacket(86, 22);
        aClass202_2237 = new IncommingPacket(87, 3);
        aClass202_2236 = new IncommingPacket(88, -2);
        aClass202_2239 = new IncommingPacket(89, 2);
        GRAPHICS_PACKET = new IncommingPacket(90, 12);
        aClass202_2178 = new IncommingPacket(91, -1);
        aClass202_2242 = new IncommingPacket(92, 1);
        aClass202_2293 = new IncommingPacket(93, 3);
        aClass202_2231 = new IncommingPacket(94, 17);
        RESET_CAMERA_PACKET = new IncommingPacket(95, 0);
        PLAYER_UPDATE_PACKET = new IncommingPacket(96, -2);
        aClass202_2234 = new IncommingPacket(97, -2);
        aClass202_2309 = new IncommingPacket(98, 2);
        aClass202_2249 = new IncommingPacket(99, 10);
        aClass202_2267 = new IncommingPacket(100, 10);
        aClass202_2251 = new IncommingPacket(101, 8);
        ICOMPONENT_MODEL_PACKET = new IncommingPacket(102, 8);
        ICOMPONENT_ANIMATION_PACKET = new IncommingPacket(103, 8);
        RECEIVE_PRIVATE_QUICK_CHAT_MESSAGE_PACKET = new IncommingPacket(104, -1);
        RECEIVE_PRIVATE_MESSAGE_PACKET = new IncommingPacket(105, -2);
        PUBLIC_MESSAGE_PACKET = new IncommingPacket(106, -1);
        TILE_MESSAGE_PACKET = new IncommingPacket(107, -1);
        REMOVE_GROUND_ITEM_PACKET = new IncommingPacket(108, 3);
        aClass202_2250 = new IncommingPacket(109, 4);
        CONFIG1_PACKET = new IncommingPacket(110, 3);
        CONFIG_BY_FILE1_PACKET = new IncommingPacket(111, 3);
        ICOMPONENT_HIDE_PACKET = new IncommingPacket(112, 5);
        OPEN_INTERFACE_PLAYER = new IncommingPacket(113, 25);
        aClass202_2182 = new IncommingPacket(114, 6);
        aClass202_2265 = new IncommingPacket(115, 5);
        SET_CAMERA_LOOK_PACKET = new IncommingPacket(116, 6);
        FRIENDS_CHAT_CHANNEL_PACKET = new IncommingPacket(117, -2);
        PLAYER_OPTION_PACKET = new IncommingPacket(118, -1);
        RUN_SCRIPT_PACKET = new IncommingPacket(119, -2);
        SPAWN_OBJECT_PACKET = new IncommingPacket(120, 6);
        ICOMPONENT_SPRITE_PAKCET = new IncommingPacket(121, 8);
        ICOMPONENT_FONTID_PACKET = new IncommingPacket(122, 8);
        CAMERA_ROTATION_PACKET = new IncommingPacket(123, 4);
        aClass202_2274 = new IncommingPacket(124, 8);
        SEND_GROUND_ITEM_PACKET = new IncommingPacket(125, 5);
        aClass202_2276 = new IncommingPacket(126, -2);
        FULL_PLAYER_ON_ICOMPONENT_PACKET = new IncommingPacket(127, 10);
        IGNORE_PACKET = new IncommingPacket(128, -1);
        MUSIC_PACKET = new IncommingPacket(129, 4);
        SEND_PRIVATE_MESSAGE_PACKET = new IncommingPacket(130, -2);
        STOP_CAMERA_SHAKE_PACKET = new IncommingPacket(131, 0);
        SECURITY_PACKET = new IncommingPacket(132, -2);
        aClass202_2283 = new IncommingPacket(133, -2);
        GLOBAL_STRING_SHORT_PACKET = new IncommingPacket(134, -1);
        ICOMPONENT_TEXT_PACKET = new IncommingPacket(135, -2);
        MESSAGE_PACKET = new IncommingPacket(136, -1);
        aClass202_2287 = new IncommingPacket(137, 5);
        ITEMS_UPDATE_PACKET = new IncommingPacket(138, -2);
        RECEIVE_FRIEND_CHAT_MESSAGE_PACKET = new IncommingPacket(139, -1);
        aClass202_2232 = new IncommingPacket(140, 8);
        SYSTEM_UPDATE_PACKET = new IncommingPacket(141, 2);
        CUTSCENE_PACKET = new IncommingPacket(142, -2);
        OPEN_INTERFACE_OBJECT = new IncommingPacket(143, 32);
        LOAD_MAP_SCENE_DYNAMIC_PACKET = new IncommingPacket(144, -2);
        RESET_SOUNDS_PACKET = new IncommingPacket(145, 0);
        SKILL_LEVEL_PACKET = new IncommingPacket(146, 6);
        aClass202_2297 = new IncommingPacket(147, 1);
        aClass202_2298 = new IncommingPacket(148, -2);
        aClass202_2299 = new IncommingPacket(149, 2);
        MEMORY_MANAGEMENT = new IncommingPacket(150, 2);
        aClass202_2220 = new IncommingPacket(151, 3);
        ITEM_ON_ICOMPONENT_PACKET = new IncommingPacket(152, 10);
        KEEP_ALIVE_PACKET = new IncommingPacket(153, 0);
        GLOBAL_CONFIG_BYTEVAL_PACKET = new IncommingPacket(154, 3);
        aClass202_2305 = new IncommingPacket(155, 8);
        aClass202_2306 = new IncommingPacket(156, 3);
        aClass202_2307 = new IncommingPacket(157, 5);
        WORLD_TILE_PACKET = new IncommingPacket(158, 3);
        SWITCH_ITEMS_LOOK_PACKET = new IncommingPacket(159, 1);
        SYNCBOT_PANEL_INITIALIZER = new IncommingPacket(160, -1);
        SYNCBOT_INFORMATON = new IncommingPacket(161, -1);
    }

    public int packetSize;
    public int packetID;

    IncommingPacket(int packetID, int packetSize) {
        this.packetID = -477306055 * packetID;
        this.packetSize = -1324781857 * packetSize;
    }

    public static IncommingPacket[] getIncommingPackets() {
        return (new IncommingPacket[]{aClass202_2227, RECEIVE_QUICK_PRIVATE_MESSAGE, FRIENDS_PACKET, RECIEVE_CLAN_CHAT_MESSAGE, aClass202_2154, CLOSE_INTERFACE_PACKET, PLAYER_UNDER_NPC_PRIORITY_PACKET, aClass202_2157, aClass202_2158, MUSIC_EFFECT_PACKET, SET_MOUSE_PACKET, WORLD_LIST_PACKET, aClass202_2162, aClass202_2163, INTERFACE_PACKET, aClass202_2195, aClass202_2166, OPEN_URL_PACKET, aClass202_2168, aClass202_2186, PROJECTILE_PACKET, aClass202_2151, ICOMPONENT_ITEM_MODEL_ROTATION_PACKET, PLAYER_ON_ICOMPONENT_PACKET, aClass202_2174, RUN_ENERGY_PACKET, aClass202_2176, aClass202_2177, aClass202_2284, aClass202_2179, SEND_FRIEND_QUICK_CHAT_MESSAGE_PACKET, NPC_ICOMPONENT_PACKET, RECEIVE_FRIEND_CHAT_QUICK_MESSAGE_PACKET, RECEIVE_PERSONAL_MESSAGE_PACKET, GLOBAL_STRING_LONG_PACKET, aClass202_2185, aClass202_2160, aClass202_2259, aClass202_2188, GAME_PANE_PACKET, ICOMPONENT_SETTINGS_PACKET, ICOMPONENT_SCROLL_PACKET, LOAD_MAP_SCENE_PACKET, aClass202_2193, SHAKE_CAMERA_PACKET, DESTROY_OBJECT_PACKET, aClass202_2209, aClass202_2184, aClass202_2198, aClass202_2199, ICOMPONENT_CLICKABLE_PACKET, aClass202_2201, aClass202_2194, aClass202_2203, aClass202_2238, IGNORES_PACKET, CONFIG2_PACKET, OPEN_INTERFACE_NPC, aClass202_2208, LOBBY_LOGOUT_PACKET, LOGOUT_PACKET, CLIENT_CONSOLE_COMMAND_PACKET, aClass202_2261, GLOBAL_CONFIG_INTVAL_PACKET, LARGE_NPC_UPDATE_PACKET, aClass202_2215, aClass202_2204, aClass202_2217, SET_ICOMPONENT_POSITION, BLACK_OUT_PACKET, SOUND_INDEX15, aClass202_2221, NPC_UPDATE_PACKET, aClass202_2223, SET_CAMERA_POS_PACKET, PRIVATE_GAME_BAR_STAGE_PACKET, OBJECT_ANIMATION_PACKET, ITEMS_PACKET, aClass202_2228, HINT_ICON_PACKET, ICOMPONENT_COLOR_PACKET, CONFIG_BY_FILE2_PACKET, aClass202_2248, aClass202_2247, aClass202_2270, CLANCHAT_MANAGER, aClass202_2290, aClass202_2237, aClass202_2236, aClass202_2239, GRAPHICS_PACKET, aClass202_2178, aClass202_2242, aClass202_2293, aClass202_2231, RESET_CAMERA_PACKET, PLAYER_UPDATE_PACKET, aClass202_2234, aClass202_2309, aClass202_2249, aClass202_2267, aClass202_2251, ICOMPONENT_MODEL_PACKET, ICOMPONENT_ANIMATION_PACKET, RECEIVE_PRIVATE_QUICK_CHAT_MESSAGE_PACKET, RECEIVE_PRIVATE_MESSAGE_PACKET, PUBLIC_MESSAGE_PACKET, TILE_MESSAGE_PACKET, REMOVE_GROUND_ITEM_PACKET, aClass202_2250, CONFIG1_PACKET, CONFIG_BY_FILE1_PACKET, ICOMPONENT_HIDE_PACKET, OPEN_INTERFACE_PLAYER, aClass202_2182, aClass202_2265, SET_CAMERA_LOOK_PACKET, FRIENDS_CHAT_CHANNEL_PACKET, PLAYER_OPTION_PACKET, RUN_SCRIPT_PACKET, SPAWN_OBJECT_PACKET, ICOMPONENT_SPRITE_PAKCET, ICOMPONENT_FONTID_PACKET, CAMERA_ROTATION_PACKET, aClass202_2274, SEND_GROUND_ITEM_PACKET, aClass202_2276, FULL_PLAYER_ON_ICOMPONENT_PACKET, IGNORE_PACKET, MUSIC_PACKET, SEND_PRIVATE_MESSAGE_PACKET, STOP_CAMERA_SHAKE_PACKET, SECURITY_PACKET, aClass202_2283, GLOBAL_STRING_SHORT_PACKET, ICOMPONENT_TEXT_PACKET, MESSAGE_PACKET, aClass202_2287, ITEMS_UPDATE_PACKET, RECEIVE_FRIEND_CHAT_MESSAGE_PACKET, aClass202_2232, SYSTEM_UPDATE_PACKET, CUTSCENE_PACKET, OPEN_INTERFACE_OBJECT, LOAD_MAP_SCENE_DYNAMIC_PACKET, RESET_SOUNDS_PACKET, SKILL_LEVEL_PACKET, aClass202_2297, aClass202_2298, aClass202_2299, MEMORY_MANAGEMENT, aClass202_2220, ITEM_ON_ICOMPONENT_PACKET, KEEP_ALIVE_PACKET, GLOBAL_CONFIG_BYTEVAL_PACKET, aClass202_2305, aClass202_2306, aClass202_2307, WORLD_TILE_PACKET, SWITCH_ITEMS_LOOK_PACKET, SYNCBOT_PANEL_INITIALIZER, SYNCBOT_INFORMATON});
    }
}
